version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clinica_ejemplo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
      PMA_PORT: 3306
    ports:
      - '8080:80'
    depends_on:
      - mysql

volumes:
  mysql_data: